[package]
name = "actix-web-rest-api-with-jwt"
version = "0.1.0"
authors = ["SakaDream <bahaimt@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0"
actix-rt = "0.2.2"
log = "0.4.6"
env_logger = "0.6.1"
diesel_migrations = "1.4.0"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"
dotenv = "0.14.1"
futures = "0.1.27"
failure = "0.1.5"
derive_more = "0.15.0"

[dependencies.diesel]
version = "1.4.2"
features = ["postgres", "r2d2", "chrono"]
