[package]
name = "actix-web-rest-api-with-jwt"
version = "0.1.0"
authors = ["SakaDream <bahaimt@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.5"
actix-rt = "0.2.4"
actix-service = "0.4.1"
log = "0.4.8"
env_logger = "0.6.2"
diesel_migrations = "1.4.0"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"
dotenv = "0.14.1"
futures = "0.1.28"
failure = "0.1.5"
derive_more = "0.15.0"
jsonwebtoken = "6.0.1"
bcrypt = "0.5.0"
time = "0.1.42"

[dependencies.diesel]
version = "1.4.2"
features = ["postgres", "r2d2", "chrono"]

[dependencies.chrono]
version = "0.4.7"
features = ["serde"]

[dependencies.uuid]
version = "0.7.4"
features = ["v4"]
