on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Get temporary secret key
        shell: sh
        run: |
          mv src/secret.key.sample src/secret.key
        
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
  
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      
      - name: Get temporary secret key
        shell: sh
        run: |
          mv src/secret.key.sample src/secret.key
      
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Get temporary secret key
        shell: sh
        run: |
          mv src/secret.key.sample src/secret.key
        
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload binary for Docker actions
        uses: actions/upload-artifact@v1
        with:
          name: artifact-linux
          path: target/release/actix-web-rest-api-with-jwt
