name: Cross-platform CICD
on: [push, pull_request]

jobs:
  cicd-linux:
    name: CICD Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Get temporary secret key
        shell: sh
        run: |
          mv src/secret.key.sample src/secret.key

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: clippy
          args: -- -D warnings

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload binary for Docker actions
        uses: actions/upload-artifact@v1
        with:
          name: artifact-linux
          path: target/release/actix-web-rest-api-with-jwt

  cicd-windows:
    name: CICD Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install postgresql
        run: |
          choco install postgresql

      - name: Get temporary secret key
        shell: cmd
        run: |
          ren src\secret.key.sample secret.key

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release
        env:
          RUSTFLAGS: -L C:/Program Files/PostgreSQL/12/lib

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: clippy
          args: -- -D warnings

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          RUSTFLAGS: -L"C:/Program Files/PostgreSQL/12/lib"

  cicd-macos:
    name: CICD macOS
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Get temporary secret key
        shell: sh
        run: |
          mv src/secret.key.sample src/secret.key

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: clippy
          args: -- -D warnings

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
