name: Cross-platform CICD
on: [push, pull_request]

jobs:
  cicd-windows:
    name: CICD Windows
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install postgresql
        run: |
          New-Item -Path "." -Name "libs" -ItemType "directory"
          Invoke-WebRequest -Uri https://sakadream.me/cloud/index.php/s/JXnJvyjifGBPuR2/download -OutFile libs\libpq.lib

      - name: Get temporary secret key
        shell: cmd
        run: |
          ren src\secret.key.sample secret.key

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: clippy
          args: -- -D warnings

      - name: Run cargo build
        shell: cmd
        run: |
          echo $RUSTFLAGS
          dir D:/a/actix-web-rest-api-with-jwt/actix-web-rest-api-with-jwt/libs
          cargo build --release
        env:
          RUSTFLAGS: -L D:\a\actix-web-rest-api-with-jwt\actix-web-rest-api-with-jwt\libs
